

export default function Head() {
  return (
    <>
      <title>Create Next App</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" sizes="32x32" href="favicon.ico" />
    </>
  )
}

//<link rel="icon" type="image/png" sizes="32x32" href="../images/sinais-de-codigo.png" />
//<link rel="icon" href="/favicon.ico" />